apiVersion: v!
kind: Pod
metadata:
  name: build-pod
spec:
  containers:
  - name: maven
    image: maven:3.8.7-openjdk-18-slim
    command:
     - cat
    tty: true
  - name: docker
    image: docker:latest
    command:
     - cat
    tty: true
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        
              

